["protostar.config"]
protostar_version = "0.2.5"

["protostar.project"]
libs_path = "lib"

["protostar.contracts"]
main = [
    "src/main.cairo",
]

[profile.testnet.protostar.deploy]
network="alpha-goerli"
